import type {Metadata} from "next";
import Navbar from "@/app/(site)/Component/Navbar/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Navbar/>
            {children}
        </>
    );
}
