import type { Metadata } from "next";
import Navbar from "@/app/(site)/profile/Component/Navbar/Navbar";
import BottomNav from "@/app/(site)/profile/Component/BottomNav/BottomNav";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
             <div className="mt-16 bg-[#f5f5f5]">
                  {children}
                 <BottomNav/>
            </div>
        </>
    );
}
